### ISSUE TITLE
Favourite when clicking "...." is displaying 

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#14]
Also why the loading bar is displaying

![image](https://user-images.githubusercontent.com/4265598/35770752-2ad19a34-0947-11e8-8fe1-81e90e689d51.png)

**Comment by kamleshKumarVerma** [comment]
@iftikharali There is some use case for Favourite button (heart icon, also we can say . like button).

1. if user is already liked(Favourite) any particular shop: red filled heart icon will be displayed. this will indicate, you have already liked this shop.

2. if user is not liked(Favourite) any particular shop: without filled heart icon will be displayed and this will indicate, you have not liked this shop.

3. Toggle is there for like and unlike shop

4. while clicking on like/ unlike button , APi call will trigger . and we will show "..."(indicating -> like/unlike is in progress) unless response come from server.

This is the expected behaviour as per my understanding .
If you have any suggestions or any doubt. please comment below .

**Comment by kamleshKumarVerma** [comment]
@iftikharali Added loading icon instead of "..."
