### ISSUE TITLE
Description in search engine is not appearing properly. 

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#55]
Take this on high priority
![image](https://user-images.githubusercontent.com/4265598/36776455-d988e63e-1c8b-11e8-819a-0a4b3a52f318.png)

**Comment by kamleshKumarVerma** [comment]
Will work in next release

On 28-Feb-2018 1:33 PM, "Iftikhar Ali Ansari" <notifications@github.com>
wrote:

Take this on high priority
[image: image]
<https://user-images.githubusercontent.com/4265598/36776455-d988e63e-1c8b-11e8-819a-0a4b3a52f318.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kamleshKumarVerma/Tendy-mart-frontend/issues/55>, or mute
the thread

**Comment by kamleshKumarVerma** [comment]
Now i worked on SEO , it will take care for it
